# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  dockerId: tylerdave
  imageName: hello-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7' 

- script: |
    pip install pipenv
    pipenv lock -r > requirements.txt
    pip install -r requirements.txt
  displayName: Install dependencies

# - script: python setup.py test
#   displayName: Run tests

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'ACR'

- task: Docker@2
  displayName: Docker Build, Tag, and Push
  inputs:
    command: buildAndPush
    repository: $(dockerId)/$(imageName)
    tags: |
      $(Build.SourceBranchName)
      1.$(Build.BuildNumber)